window.APP_CONFIG = {
  scheduleName: "Chris' Schedule",
  subtitle: "Elastisched",
  minuteGranularity: 5,
  tasksDisplayDays: 3,
  finishEarlyBufferMinutes: 15,
  includeActiveOccurrences: true,
  lookaheadSeconds: 14 * 24 * 60 * 60,
  dayEndsAtMinutes: 0,
  projectTimeZone: "UTC",
  theme: "sand",
  engineInitialTemp: 10.0,
  engineFinalTemp: 0.0001,
  engineNumIters: 1000000,
  engineAdvancedEnabled: false,
  engineIllegalScheduleWeight: 1.0,
  engineOverlapCostWeight: 1.0,
  engineSplitCostWeight: 1.0,
  engineConsistencyCostWeight: 1.0,
  engineGranularityCostWeight: 1.0,
  keybinds: {
    undo: "Mod+Z",
    redo: "Mod+Y",
    closePanels: "Escape",
    createTask: "N",
    createEvent: "C",
    goToday: "T",
    navigatePrev: "ArrowLeft",
    navigateNext: "ArrowRight",
  },
};
