window.APP_CONFIG = {
  scheduleName: "Chris' Schedule",
  subtitle: "Elastisched",
  minuteGranularity: 5,
  finishEarlyBufferMinutes: 15,
  includeActiveOccurrences: true,
  lookaheadSeconds: 14 * 24 * 60 * 60,
  projectTimeZone: "UTC",
  theme: "sand",
  engineInitialTemp: 10.0,
  engineFinalTemp: 0.0001,
  engineNumIters: 1000000,
  engineAdvancedEnabled: false,
  engineIllegalScheduleWeight: 1.0,
  engineOverlapCostWeight: 1.0,
  engineSplitCostWeight: 1.0,
};
